Feature/skills section
olek-byte/cuda pull request #1
Opened 2022-05-04 10:26 UTC by olek-byte

2022-05-04 10:27 UTC, olek-byte commented
Hello

2022-05-04 10:33 UTC, ArtyomKoroteev commented on css/_global.css
> +  cursor: pointer;
I recommend you to add default hover state for button. For example:
button::hover {
 opacity: 0.8;
}

2022-05-06 08:14 UTC, ArtyomKoroteev requested changes

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_footer.css
> +    background-color: #344b8e;
should be variable

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_form.css
> +    background-color: #3c5499;
You have to put valut into variable across this file

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_form.css
> +    background-color: #273a71;
same

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_form.css
> +  color: #fff;
same

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_form.css
> +   background-color: #273a71;
same

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_form.css
> +        width: 600px;
better use max-width and width 100%. Be careful with width

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_form.css
> +    height: 200px;
the same thing with height

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_team.css
>  .team-social__inner {
empty block, remove it

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_team.css
> +    fill: #77cfec;
put color into variable

2022-05-06 08:14 UTC, ArtyomKoroteev commented on css/components/_team.css
>  @media (max-width: 480px) {
empty block

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/testModule.js
> +export const testModule = (() => {
remove this file and import for it

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/smoothScrollModule.js
> +        listActive.classList.remove('header__list--active');
If you add, remove or toggle class, I recommend you put the value of class into variable in such notation:
const HEADER_LIST_ACTIVE_CLASS = 'header__list--active';

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/smoothScrollModule.js
> +        burger.classList.remove('burger--click');
the same

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/smoothScrollModule.js
> +    for (const link of links) {
Better use forEach, for example.
 links.forEach((link) => {
        
});

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/pageScrollModule.js
> +    window.onscroll = function () {
Use addEventListener

Pack event into separate function

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/pageScrollModule.js
> +            header.classList.add('sticky');
'sticky' have to be a variable

2022-05-06 08:14 UTC, ArtyomKoroteev commented on index.html
> +                    Tel: (202) 456-1111
pack telephone into `<a href="tel:+6494461709">61709</a>`

2022-05-06 08:14 UTC, ArtyomKoroteev commented on js/modules/headerModule.js
> +        burger.classList.toggle('burger--click');
toggle classes have to be variables

2022-06-14 17:44 UTC, merged